import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AI } from "@/app/actions";
import { MyRuntimeProvider } from "@/app/MyRuntimeProvider";
import type React from "react";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AI>
        <MyRuntimeProvider>
          <body
            className={inter.className}
            style={{ backgroundColor: "transparent" }}
          >
            {children}
          </body>
        </MyRuntimeProvider>
      </AI>
    </html>
  );
}
