name: TestDriver.ai

on:
  workflow_run:
    workflows: ["Changesets"]
    types:
      - completed
    branches:
      - main

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@main
        with:
          key: ${{secrets.TESTDRIVER_API_KEY}}
          prompt: |
            1. /run testdriver/test.yml
          prerun: |
            cd $env:TEMP
            echo "my-app" | npx assistant-ui create
            cd my-app
            npm install dashcam-chrome
            echo "creating .env file and setting OPENAI_API_KEY"
            Set-Content -Path ".env" -Value "OPENAI_API_KEY=${{env.OPENAI_API_KEY}}"
            echo "starting dev server"
            Start-Process -NoNewWindow -PassThru "npm" -ArgumentList "run", "dev"
            echo "starting chrome"
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized", "--load-extension=$(pwd)/node_modules/dashcam-chrome/build", "${{env.LOCALHOST_URL}}"
            exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LOCALHOST_URL: "http://localhost:3000"